/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/restore-preview-modal.ts
var restore_preview_modal_exports = {};
__export(restore_preview_modal_exports, {
  RestorePreviewModal: () => RestorePreviewModal
});
var import_obsidian4, RestorePreviewModal;
var init_restore_preview_modal = __esm({
  "src/restore-preview-modal.ts"() {
    import_obsidian4 = require("obsidian");
    RestorePreviewModal = class extends import_obsidian4.Modal {
      constructor(app, client, sourceId, filePath, version, versionLabel, repoPath, onRestore) {
        super(app);
        this.client = client;
        this.sourceId = sourceId;
        this.filePath = filePath;
        this.version = version;
        this.versionLabel = versionLabel;
        this.repoPath = repoPath;
        this.onRestore = onRestore;
      }
      async onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("ginkgo-restore-modal");
        const headerEl = contentEl.createEl("div", { cls: "ginkgo-header" });
        headerEl.createEl("span", { cls: "ginkgo-header-title", text: "\u6062\u590D\u9884\u89C8" });
        const infoEl = contentEl.createEl("div", { cls: "ginkgo-restore-info" });
        infoEl.createEl("div", { text: `\u6587\u4EF6: ${this.filePath}`, cls: "ginkgo-restore-path" });
        infoEl.createEl("div", { text: `\u7248\u672C: ${this.versionLabel}`, cls: "ginkgo-restore-version" });
        infoEl.createEl("div", { text: `\u5927\u5C0F: ${this.formatBytes(this.version.size)}`, cls: "ginkgo-restore-size" });
        if (this.version.is_deleted) {
          infoEl.createEl("div", { text: "\u26A0\uFE0F \u6B64\u7248\u672C\u4E3A\u5220\u9664\u72B6\u6001", cls: "ginkgo-restore-deleted" });
        }
        const loadingEl = contentEl.createEl("div", { cls: "ginkgo-loading" });
        loadingEl.createEl("span", { text: "\u52A0\u8F7D\u6587\u4EF6\u5185\u5BB9..." });
        let content = "";
        try {
          const snapshotTime = this.version.last_seen > 9e12 ? this.version.first_seen : this.version.last_seen;
          const resp = await this.client.getFileContent(
            this.sourceId,
            this.filePath,
            snapshotTime,
            this.repoPath
          );
          if (resp.content) {
            try {
              content = decodeURIComponent(escape(atob(resp.content)));
            } catch (e) {
              content = resp.content;
            }
          }
          if (resp.error) {
            content = `(\u8BFB\u53D6\u5931\u8D25: ${resp.error})`;
          }
          if (!content) {
            content = "(\u7A7A\u6587\u4EF6)";
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          content = `(\u65E0\u6CD5\u83B7\u53D6\u5185\u5BB9: ${msg})`;
        }
        loadingEl.remove();
        const previewEl = contentEl.createEl("div", { cls: "ginkgo-restore-preview" });
        const codeEl = previewEl.createEl("pre", { cls: "ginkgo-restore-code" });
        const lines = content.split("\n");
        const maxLines = 100;
        const displayContent = lines.slice(0, maxLines).join("\n");
        codeEl.createEl("code", { text: displayContent });
        if (lines.length > maxLines) {
          previewEl.createEl("div", {
            cls: "ginkgo-restore-truncated",
            text: `... \u5171 ${lines.length} \u884C\uFF0C\u4EC5\u663E\u793A\u524D ${maxLines} \u884C`
          });
        }
        const warningEl = contentEl.createEl("div", { cls: "ginkgo-restore-warning" });
        warningEl.createEl("span", { text: "\u26A0\uFE0F \u6062\u590D\u5C06\u8986\u76D6\u5F53\u524D\u6587\u4EF6\u5185\u5BB9" });
        const footerEl = contentEl.createEl("div", { cls: "ginkgo-modal-footer" });
        const restoreBtn = footerEl.createEl("button", {
          cls: "ginkgo-btn-restore",
          text: "\u786E\u8BA4\u6062\u590D"
        });
        restoreBtn.addEventListener("click", async () => {
          restoreBtn.disabled = true;
          restoreBtn.textContent = "\u6062\u590D\u4E2D...";
          try {
            await this.onRestore();
            this.close();
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian4.Notice(`Ginkgo: \u6062\u590D\u5931\u8D25 \u2014 ${msg}`);
            restoreBtn.disabled = false;
            restoreBtn.textContent = "\u786E\u8BA4\u6062\u590D";
          }
        });
        footerEl.createEl("button", { cls: "ginkgo-close-btn", text: "\u53D6\u6D88" }).addEventListener("click", () => this.close());
      }
      formatBytes(bytes) {
        if (!bytes || isNaN(bytes))
          return "0 B";
        if (bytes < 1024)
          return `${bytes} B`;
        if (bytes < 1048576)
          return `${(bytes / 1024).toFixed(1)} KB`;
        if (bytes < 1073741824)
          return `${(bytes / 1048576).toFixed(1)} MB`;
        return `${(bytes / 1073741824).toFixed(1)} GB`;
      }
      onClose() {
        this.contentEl.empty();
      }
    };
  }
});

// src/file-history-modal.ts
var file_history_modal_exports = {};
__export(file_history_modal_exports, {
  FileHistoryModal: () => FileHistoryModal
});
function computeLCS(oldLines, newLines) {
  const m = oldLines.length;
  const n = newLines.length;
  if (m === 0)
    return newLines.map((l) => ({ type: "added", text: l }));
  if (n === 0)
    return oldLines.map((l) => ({ type: "removed", text: l }));
  if (m * n > 4e6)
    return computeSimpleDiff(oldLines, newLines);
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i2 = 1; i2 <= m; i2++) {
    for (let j2 = 1; j2 <= n; j2++) {
      dp[i2][j2] = oldLines[i2 - 1] === newLines[j2 - 1] ? dp[i2 - 1][j2 - 1] + 1 : Math.max(dp[i2 - 1][j2], dp[i2][j2 - 1]);
    }
  }
  const result = [];
  let i = m, j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && oldLines[i - 1] === newLines[j - 1]) {
      result.unshift({ type: "unchanged", text: oldLines[i - 1] });
      i--;
      j--;
    } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
      result.unshift({ type: "added", text: newLines[j - 1] });
      j--;
    } else {
      result.unshift({ type: "removed", text: oldLines[i - 1] });
      i--;
    }
  }
  return result;
}
function computeSimpleDiff(oldLines, newLines) {
  const result = [];
  const maxLen = Math.max(oldLines.length, newLines.length);
  for (let i = 0; i < maxLen; i++) {
    const oLine = i < oldLines.length ? oldLines[i] : void 0;
    const nLine = i < newLines.length ? newLines[i] : void 0;
    if (oLine !== void 0 && nLine !== void 0 && oLine === nLine) {
      result.push({ type: "unchanged", text: oLine });
    } else {
      if (oLine !== void 0)
        result.push({ type: "removed", text: oLine });
      if (nLine !== void 0)
        result.push({ type: "added", text: nLine });
    }
  }
  return result;
}
function extractDiffOnly(lines, contextLines) {
  const changeIndices = [];
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].type !== "unchanged")
      changeIndices.push(i);
  }
  if (changeIndices.length === 0)
    return [];
  const included = /* @__PURE__ */ new Set();
  for (const idx of changeIndices) {
    for (let c = -contextLines; c <= contextLines; c++) {
      const target = idx + c;
      if (target >= 0 && target < lines.length)
        included.add(target);
    }
  }
  const sorted = [...included].sort((a, b) => a - b);
  const result = [];
  let lastIdx = -2;
  for (const idx of sorted) {
    if (idx > lastIdx + 1) {
      result.push({ type: "unchanged", text: "..." });
    }
    result.push(lines[idx]);
    lastIdx = idx;
  }
  return result;
}
var import_obsidian5, FileHistoryModal;
var init_file_history_modal = __esm({
  "src/file-history-modal.ts"() {
    import_obsidian5 = require("obsidian");
    FileHistoryModal = class extends import_obsidian5.Modal {
      constructor(app, client, sourceId, filePath, repoPath) {
        super(app);
        this.versions = [];
        this.selectedIdx = null;
        this.compareIdx = null;
        this.currentContent = "";
        this.client = client;
        this.sourceId = sourceId;
        this.filePath = filePath;
        this.repoPath = repoPath;
      }
      async onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("ginkgo-file-history-modal");
        const modalEl = contentEl.closest(".modal");
        if (modalEl) {
          modalEl.style.width = "800px";
          modalEl.style.maxWidth = "90vw";
        }
        this.renderHeader(contentEl);
        const loadingEl = contentEl.createEl("div", { cls: "ginkgo-loading" });
        loadingEl.createEl("span", { text: "\u52A0\u8F7D\u4E2D..." });
        try {
          const [versions, currentContent] = await Promise.all([
            this.client.getFileHistory(this.sourceId, this.filePath, this.repoPath),
            this.readCurrentFile()
          ]);
          this.versions = versions;
          this.currentContent = currentContent;
          loadingEl.remove();
          if (this.versions.length === 0) {
            contentEl.createEl("div", { cls: "ginkgo-empty", text: "\u6682\u65E0\u5907\u4EFD\u5386\u53F2" });
            return;
          }
          this.renderBody(contentEl);
        } catch (err) {
          loadingEl.remove();
          const msg = err instanceof Error ? err.message : String(err);
          contentEl.createEl("div", { cls: "ginkgo-error", text: `\u52A0\u8F7D\u5931\u8D25: ${msg}` });
        }
      }
      renderHeader(contentEl) {
        const headerEl = contentEl.createEl("div", { cls: "ginkgo-fh-header" });
        headerEl.createEl("span", { cls: "ginkgo-fh-title", text: "\u7248\u672C\u5386\u53F2" });
        headerEl.createEl("span", { cls: "ginkgo-fh-filename", text: this.getFileName() });
      }
      renderBody(contentEl) {
        const bodyEl = contentEl.createEl("div", { cls: "ginkgo-fh-body" });
        const leftEl = bodyEl.createEl("div", { cls: "ginkgo-fh-versions" });
        leftEl.createEl("div", { cls: "ginkgo-fh-section-label", text: `\u5171 ${this.versions.length} \u4E2A\u7248\u672C \xB7 \u70B9\u51FB\u9009\u62E9\uFF0C\u518D\u70B9\u51FB\u53E6\u4E00\u7248\u672C\u7684\u300C\u5BF9\u6BD4\u300D` });
        this.listEl = leftEl.createEl("div", { cls: "ginkgo-fh-list" });
        this.renderVersionList();
        const rightEl = bodyEl.createEl("div", { cls: "ginkgo-fh-preview" });
        const diffHeaderEl = rightEl.createEl("div", { cls: "ginkgo-fh-section-label", text: "\u5DEE\u5F02" });
        this.diffEl = rightEl.createEl("div", { cls: "ginkgo-fh-diff" });
        this.diffEl.createEl("div", { cls: "ginkgo-fh-diff-empty", text: "\u70B9\u51FB\u5DE6\u4FA7\u7248\u672C\u67E5\u770B\u4E0E\u5F53\u524D\u6587\u4EF6\u7684\u5DEE\u5F02" });
        const footerEl = contentEl.createEl("div", { cls: "ginkgo-fh-footer" });
        this.restoreBtn = footerEl.createEl("button", {
          cls: "ginkgo-btn-restore",
          text: "\u6062\u590D\u6B64\u7248\u672C"
        });
        this.restoreBtn.disabled = true;
        this.restoreBtn.addEventListener("click", () => this.restoreSelectedVersion());
        footerEl.createEl("button", { cls: "ginkgo-close-btn", text: "\u5173\u95ED" }).addEventListener("click", () => this.close());
      }
      isSentinelTs(ts) {
        return ts > 9e12;
      }
      effectiveTs(version) {
        if (this.isSentinelTs(version.last_seen)) {
          return version.first_seen;
        }
        return version.last_seen;
      }
      tsToDate(ts) {
        if (ts > 1e15)
          return new Date(ts / 1e6);
        return new Date(ts);
      }
      renderVersionList() {
        this.listEl.empty();
        for (let i = 0; i < this.versions.length; i++) {
          const version = this.versions[i];
          const isLatest = i === 0;
          const isFirst = i === this.versions.length - 1;
          const isSelected = this.selectedIdx === i;
          const isComparing = this.compareIdx === i;
          const isCurrent = this.isSentinelTs(version.last_seen);
          const itemEl = this.listEl.createEl("div", {
            cls: `ginkgo-fh-item ${isSelected ? "is-selected" : ""} ${isComparing ? "is-comparing" : ""}`
          });
          const trackEl = itemEl.createEl("div", { cls: "ginkgo-fh-track" });
          if (isComparing) {
            const markerEl = trackEl.createEl("div", { cls: "ginkgo-fh-compare-marker" });
            (0, import_obsidian5.setIcon)(markerEl, "git-branch");
          } else if (isSelected) {
            const checkEl = trackEl.createEl("div", { cls: "ginkgo-fh-check" });
            (0, import_obsidian5.setIcon)(checkEl, "check");
          } else {
            trackEl.createEl("div", { cls: `ginkgo-fh-dot ${isLatest ? "is-latest" : ""} ${isCurrent ? "is-current" : ""}` });
          }
          const infoEl = itemEl.createEl("div", { cls: "ginkgo-fh-info" });
          infoEl.addEventListener("click", () => this.handleSelect(i));
          const timeEl = infoEl.createEl("div", { cls: "ginkgo-fh-time" });
          if (isCurrent) {
            timeEl.createEl("span", { cls: "ginkgo-fh-reltime", text: "\u5F53\u524D\u7248\u672C" });
            timeEl.createEl("span", { cls: "ginkgo-fh-abstime", text: this.formatTime(version.first_seen) });
          } else {
            timeEl.createEl("span", { cls: "ginkgo-fh-reltime", text: this.relativeTime(version.last_seen) });
            timeEl.createEl("span", { cls: "ginkgo-fh-abstime", text: this.formatTime(version.last_seen) });
          }
          const metaEl = infoEl.createEl("div", { cls: "ginkgo-fh-meta" });
          metaEl.createEl("span", { cls: "ginkgo-fh-size", text: this.formatBytes(version.size) });
          if (isLatest && !isCurrent) {
            metaEl.createEl("span", { cls: "ginkgo-fh-badge ginkgo-fh-badge-latest", text: "\u6700\u65B0" });
          } else if (isFirst) {
            metaEl.createEl("span", { cls: "ginkgo-fh-badge ginkgo-fh-badge-first", text: "\u9996\u6B21" });
          } else if (i < this.versions.length - 1) {
            const prevSize = this.versions[i + 1].size;
            const delta = version.size - prevSize;
            if (delta !== 0) {
              const isUp = delta > 0;
              metaEl.createEl("span", {
                cls: `ginkgo-fh-delta ${isUp ? "is-up" : "is-down"}`,
                text: `${isUp ? "+" : ""}${this.formatBytes(delta)}`
              });
            }
          }
          if (version.is_deleted) {
            metaEl.createEl("span", { cls: "ginkgo-fh-badge ginkgo-fh-badge-deleted", text: "\u5DF2\u5220\u9664" });
          }
          if (isSelected) {
            metaEl.createEl("span", { cls: "ginkgo-fh-badge ginkgo-fh-badge-b", text: "B" });
          }
          if (isComparing) {
            metaEl.createEl("span", { cls: "ginkgo-fh-badge ginkgo-fh-badge-a", text: "A" });
          }
          if (this.selectedIdx !== null && i !== this.selectedIdx) {
            const compareBtn = itemEl.createEl("button", {
              cls: `ginkgo-fh-compare-btn ${isComparing ? "is-active" : ""}`,
              text: isComparing ? "\u53D6\u6D88" : "\u5BF9\u6BD4"
            });
            compareBtn.addEventListener("click", (e) => {
              e.stopPropagation();
              this.handleCompare(i);
            });
          }
        }
      }
      handleSelect(idx) {
        if (this.selectedIdx === idx) {
          this.selectedIdx = null;
          this.compareIdx = null;
        } else {
          this.selectedIdx = idx;
        }
        this.renderVersionList();
        this.restoreBtn.disabled = this.selectedIdx === null;
        if (this.selectedIdx !== null && this.compareIdx !== null && this.selectedIdx !== this.compareIdx) {
          this.loadCompareDiff();
        } else if (this.selectedIdx !== null) {
          this.loadCurrentDiff();
        } else {
          this.diffEl.empty();
          this.diffEl.createEl("div", { cls: "ginkgo-fh-diff-empty", text: "\u70B9\u51FB\u5DE6\u4FA7\u7248\u672C\u67E5\u770B\u5DEE\u5F02" });
        }
      }
      handleCompare(idx) {
        if (this.compareIdx === idx) {
          this.compareIdx = null;
        } else {
          this.compareIdx = idx;
        }
        this.renderVersionList();
        if (this.selectedIdx !== null && this.compareIdx !== null && this.selectedIdx !== this.compareIdx) {
          this.loadCompareDiff();
        } else if (this.selectedIdx !== null) {
          this.loadCurrentDiff();
        }
      }
      async loadCurrentDiff() {
        if (this.selectedIdx === null)
          return;
        const version = this.versions[this.selectedIdx];
        this.diffEl.empty();
        this.diffEl.createEl("div", { cls: "ginkgo-fh-diff-loading", text: "\u52A0\u8F7D\u5DEE\u5F02..." });
        try {
          if (this.isSentinelTs(version.last_seen)) {
            this.renderDiff(this.diffEl, this.currentContent, this.currentContent, "\u5F53\u524D\u7248\u672C", "\u5F53\u524D\u7248\u672C");
            return;
          }
          const snapshotTime = this.effectiveTs(version);
          const resp = await this.client.getFileContent(this.sourceId, this.filePath, snapshotTime, this.repoPath);
          let versionContent = "";
          if (resp.content) {
            try {
              versionContent = decodeURIComponent(escape(atob(resp.content)));
            } catch (e) {
              versionContent = resp.content;
            }
          }
          if (resp.error) {
            this.diffEl.empty();
            this.diffEl.createEl("div", { cls: "ginkgo-error", text: `\u5185\u5BB9\u8BFB\u53D6\u5931\u8D25: ${resp.error}` });
            return;
          }
          this.renderDiff(this.diffEl, versionContent, this.currentContent, this.formatTime(version.first_seen), "\u5F53\u524D\u6587\u4EF6");
        } catch (err) {
          this.diffEl.empty();
          const msg = err instanceof Error ? err.message : String(err);
          this.diffEl.createEl("div", { cls: "ginkgo-error", text: `\u52A0\u8F7D\u5931\u8D25: ${msg}` });
        }
      }
      async loadCompareDiff() {
        if (this.selectedIdx === null || this.compareIdx === null)
          return;
        const aVersion = this.versions[this.compareIdx];
        const bVersion = this.versions[this.selectedIdx];
        this.diffEl.empty();
        this.diffEl.createEl("div", { cls: "ginkgo-fh-diff-loading", text: "\u52A0\u8F7D\u4E24\u4E2A\u7248\u672C..." });
        try {
          const [aResp, bResp] = await Promise.all([
            this.isSentinelTs(aVersion.last_seen) ? { content: btoa(unescape(encodeURIComponent(this.currentContent))), error: "" } : this.client.getFileContent(this.sourceId, this.filePath, this.effectiveTs(aVersion), this.repoPath),
            this.isSentinelTs(bVersion.last_seen) ? { content: btoa(unescape(encodeURIComponent(this.currentContent))), error: "" } : this.client.getFileContent(this.sourceId, this.filePath, this.effectiveTs(bVersion), this.repoPath)
          ]);
          let aContent = "";
          let bContent = "";
          if (aResp.content) {
            try {
              aContent = decodeURIComponent(escape(atob(aResp.content)));
            } catch (e) {
              aContent = aResp.content;
            }
          }
          if (bResp.content) {
            try {
              bContent = decodeURIComponent(escape(atob(bResp.content)));
            } catch (e) {
              bContent = bResp.content;
            }
          }
          const aLabel = this.isSentinelTs(aVersion.last_seen) ? "\u5F53\u524D\u7248\u672C" : this.formatTime(aVersion.first_seen);
          const bLabel = this.isSentinelTs(bVersion.last_seen) ? "\u5F53\u524D\u7248\u672C" : this.formatTime(bVersion.first_seen);
          this.renderDiff(this.diffEl, aContent, bContent, aLabel, bLabel);
        } catch (err) {
          this.diffEl.empty();
          const msg = err instanceof Error ? err.message : String(err);
          this.diffEl.createEl("div", { cls: "ginkgo-error", text: `\u52A0\u8F7D\u5931\u8D25: ${msg}` });
        }
      }
      renderDiff(container, oldContent, newContent, oldLabel, newLabel) {
        container.empty();
        const normalizedOld = oldContent.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
        const normalizedNew = newContent.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
        const oldLines = normalizedOld.split("\n");
        const newLines = normalizedNew.split("\n");
        if (oldLines.length > 0 && oldLines[oldLines.length - 1] === "")
          oldLines.pop();
        if (newLines.length > 0 && newLines[newLines.length - 1] === "")
          newLines.pop();
        const diffLines = computeLCS(oldLines, newLines);
        let added = 0;
        let removed = 0;
        for (const l of diffLines) {
          if (l.type === "added")
            added++;
          else if (l.type === "removed")
            removed++;
        }
        const headerEl = container.createEl("div", { cls: "ginkgo-fh-diff-header" });
        const labelEl = headerEl.createEl("div", { cls: "ginkgo-fh-diff-labels" });
        labelEl.createEl("span", { cls: "ginkgo-fh-diff-label-a", text: `A: ${oldLabel}` });
        const arrowEl = labelEl.createEl("span", { cls: "ginkgo-fh-diff-arrow" });
        (0, import_obsidian5.setIcon)(arrowEl, "arrow-right");
        labelEl.createEl("span", { cls: "ginkgo-fh-diff-label-b", text: `B: ${newLabel}` });
        if (added === 0 && removed === 0) {
          headerEl.createEl("span", { cls: "ginkgo-fh-diff-identical", text: "\u5185\u5BB9\u76F8\u540C" });
          return;
        }
        const statsEl = headerEl.createEl("div", { cls: "ginkgo-fh-diff-stats" });
        if (removed > 0)
          statsEl.createEl("span", { cls: "ginkgo-fh-stat-remove", text: `-${removed}` });
        if (added > 0)
          statsEl.createEl("span", { cls: "ginkgo-fh-stat-add", text: `+${added}` });
        const diffOnly = extractDiffOnly(diffLines, 1);
        const codeEl = container.createEl("div", { cls: "ginkgo-fh-diff-code" });
        for (const line of diffOnly) {
          const lineEl = codeEl.createEl("div", {
            cls: `ginkgo-fh-diff-line ${line.type === "added" ? "is-add" : line.type === "removed" ? "is-remove" : line.text === "..." ? "is-fold" : "is-same"}`
          });
          if (line.text === "...") {
            lineEl.createEl("span", { cls: "ginkgo-fh-diff-fold-text", text: "\u22EF" });
            continue;
          }
          const signEl = lineEl.createEl("span", { cls: "ginkgo-fh-diff-sign" });
          signEl.setText(line.type === "added" ? "+" : line.type === "removed" ? "-" : " ");
          lineEl.createEl("span", { cls: "ginkgo-fh-diff-content" }).setText(line.text);
        }
      }
      async restoreSelectedVersion() {
        if (this.selectedIdx === null)
          return;
        const version = this.versions[this.selectedIdx];
        const snapshotTime = this.effectiveTs(version);
        const versionLabel = this.isSentinelTs(version.last_seen) ? "\u5F53\u524D\u7248\u672C" : this.formatTime(version.last_seen);
        const { RestorePreviewModal: RestorePreviewModal2 } = await Promise.resolve().then(() => (init_restore_preview_modal(), restore_preview_modal_exports));
        const modal = new RestorePreviewModal2(
          this.app,
          this.client,
          this.sourceId,
          this.filePath,
          version,
          versionLabel,
          this.repoPath,
          async () => {
            try {
              const resp = await this.client.getFileContent(this.sourceId, this.filePath, snapshotTime, this.repoPath);
              let versionContent = "";
              if (resp.content) {
                try {
                  versionContent = decodeURIComponent(escape(atob(resp.content)));
                } catch (e) {
                  versionContent = resp.content;
                }
              }
              let file = this.app.vault.getAbstractFileByPath(this.filePath);
              if (!file) {
                const allFiles = this.app.vault.getFiles();
                const matches = allFiles.filter((f) => f.name === this.filePath || f.path.endsWith("/" + this.filePath) || f.path === this.filePath);
                if (matches.length > 0)
                  file = matches[0];
              }
              if (file instanceof import_obsidian5.TFile) {
                await this.app.vault.modify(file, versionContent);
              } else {
                const dirPath = this.filePath.includes("/") ? this.filePath.substring(0, this.filePath.lastIndexOf("/")) : "";
                if (dirPath)
                  await this.app.vault.createFolder(dirPath).catch(() => {
                  });
                await this.app.vault.create(this.filePath, versionContent);
              }
              this.currentContent = versionContent;
              new import_obsidian5.Notice("Ginkgo: \u6587\u4EF6\u5DF2\u6062\u590D");
              this.close();
            } catch (err) {
              const msg = err instanceof Error ? err.message : String(err);
              new import_obsidian5.Notice(`Ginkgo: \u6062\u590D\u5931\u8D25 \u2014 ${msg}`);
            }
          }
        );
        modal.open();
      }
      async readCurrentFile() {
        try {
          let file = this.app.vault.getAbstractFileByPath(this.filePath);
          if (!file) {
            const allFiles = this.app.vault.getFiles();
            const matches = allFiles.filter((f) => f.name === this.filePath || f.path.endsWith("/" + this.filePath) || f.path === this.filePath);
            if (matches.length > 0)
              file = matches[0];
          }
          if (!file || !(file instanceof import_obsidian5.TFile))
            return "";
          return await this.app.vault.read(file);
        } catch (e) {
          return "";
        }
      }
      getFileName() {
        const parts = this.filePath.split(/[/\\]/);
        return parts[parts.length - 1] || this.filePath;
      }
      relativeTime(ts) {
        const date = this.tsToDate(ts);
        if (isNaN(date.getTime()))
          return String(ts);
        const now = new Date();
        const diffMs = now.getTime() - date.getTime();
        const diffSec = Math.floor(diffMs / 1e3);
        const diffMin = Math.floor(diffSec / 60);
        const diffHour = Math.floor(diffMin / 60);
        const diffDay = Math.floor(diffHour / 24);
        if (diffSec < 60)
          return "\u521A\u521A";
        if (diffMin < 60)
          return `${diffMin} \u5206\u949F\u524D`;
        if (diffHour < 24)
          return `${diffHour} \u5C0F\u65F6\u524D`;
        const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        const targetDay = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        const dayDiff = Math.floor((today.getTime() - targetDay.getTime()) / 864e5);
        if (dayDiff === 0)
          return "\u4ECA\u5929";
        if (dayDiff === 1)
          return "\u6628\u5929";
        if (dayDiff < 7)
          return `${dayDiff} \u5929\u524D`;
        if (dayDiff < 30)
          return `${Math.floor(dayDiff / 7)} \u5468\u524D`;
        const m = String(date.getMonth() + 1).padStart(2, "0");
        const d = String(date.getDate()).padStart(2, "0");
        return `${date.getFullYear()}-${m}-${d}`;
      }
      formatTime(ts) {
        const date = this.tsToDate(ts);
        if (isNaN(date.getTime()))
          return String(ts);
        return date.toLocaleString();
      }
      formatBytes(bytes) {
        if (!bytes || isNaN(bytes))
          return "0 B";
        const sign = bytes < 0 ? "-" : "";
        bytes = Math.abs(bytes);
        if (bytes === 0)
          return "0 B";
        const k = 1024;
        const sizes = ["B", "KB", "MB", "GB"];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return sign + parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + " " + sizes[Math.min(i, sizes.length - 1)];
      }
      onClose() {
        this.contentEl.empty();
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GinkgoBackupPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  apiHost: "127.0.0.1",
  apiPort: 9275,
  apiToken: "",
  refreshInterval: 60,
  showStatusBar: true,
  autoBackupOnSave: false,
  autoBackupDebounceMs: 3e4,
  stagingPushOnSave: true,
  sourceId: 0,
  excludePaths: [".obsidian", ".trash", ".DS_Store"],
  watchExtensions: ["md", "canvas", "base", "json", "css"],
  vaultIdentifier: ""
};
var GinkgoApiError = class extends Error {
  constructor(type, message, statusCode = 0, code = "") {
    super(message);
    this.name = "GinkgoApiError";
    this.type = type;
    this.statusCode = statusCode;
    this.code = code;
  }
  get userMessage() {
    switch (this.type) {
      case "network" /* NETWORK */:
        return "Ginkgo Backup \u672A\u8FD0\u884C\uFF0C\u8BF7\u786E\u4FDD\u5E94\u7528\u5DF2\u542F\u52A8";
      case "auth" /* AUTH */:
        return "API Token \u65E0\u6548\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u68C0\u67E5 Token";
      case "not_found" /* NOT_FOUND */:
        return "\u5907\u4EFD\u6E90\u672A\u627E\u5230\uFF0C\u8BF7\u91CD\u65B0\u914D\u7F6E";
      case "rate_limited" /* RATE_LIMITED */:
        return "\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5";
      case "bad_request" /* BAD_REQUEST */:
        return `\u8BF7\u6C42\u9519\u8BEF: ${this.message}`;
      case "server" /* SERVER */:
        return `\u670D\u52A1\u5668\u9519\u8BEF: ${this.message}`;
      default:
        return this.message;
    }
  }
};

// src/api.ts
var GinkgoBackupClient = class {
  constructor(host, port, token) {
    this.baseURL = this.buildBaseURL(host, port);
    this.token = token;
  }
  updateConfig(host, port, token) {
    this.baseURL = this.buildBaseURL(host, port);
    this.token = token;
  }
  buildBaseURL(host, port) {
    if (host.startsWith("http://") || host.startsWith("https://")) {
      const url = new URL(host);
      if (port && !host.includes(":" + port)) {
        url.port = String(port);
      }
      return `${url.origin}/api/v1`;
    }
    return `http://${host}:${port}/api/v1`;
  }
  async request(method, path, body) {
    var _a, _b, _c, _d;
    const opts = {
      url: `${this.baseURL}${path}`,
      method,
      headers: {
        "X-Ginkgo-Token": this.token,
        "Content-Type": "application/json"
      },
      throw: false
    };
    if (body !== void 0) {
      opts.body = JSON.stringify(body);
    }
    let resp;
    try {
      resp = await (0, import_obsidian.requestUrl)(opts);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("net::ERR_CONNECTION_REFUSED") || msg.includes("ECONNREFUSED") || msg.includes("fetch") || msg.includes("connect") || msg.includes("timeout") || msg.includes("Timeout")) {
        throw new GinkgoApiError("network" /* NETWORK */, "Cannot connect to Ginkgo Backup");
      }
      throw new GinkgoApiError("network" /* NETWORK */, msg);
    }
    const status = resp.status;
    if (status === 0) {
      throw new GinkgoApiError("network" /* NETWORK */, "Cannot connect to Ginkgo Backup");
    }
    if (status === 401) {
      throw new GinkgoApiError("auth" /* AUTH */, "Invalid API token", 401, "unauthorized");
    }
    if (status === 429) {
      throw new GinkgoApiError("rate_limited" /* RATE_LIMITED */, "Too many requests", 429, "rate_limited");
    }
    if (status >= 400) {
      const errData = resp.json;
      const code = (_b = (_a = errData == null ? void 0 : errData.error) == null ? void 0 : _a.code) != null ? _b : "";
      const message = (_d = (_c = errData == null ? void 0 : errData.error) == null ? void 0 : _c.message) != null ? _d : `HTTP ${status}`;
      if (status === 404) {
        throw new GinkgoApiError("not_found" /* NOT_FOUND */, message, 404, code);
      }
      if (status === 400) {
        throw new GinkgoApiError("bad_request" /* BAD_REQUEST */, message, 400, code);
      }
      if (status >= 500) {
        throw new GinkgoApiError("server" /* SERVER */, message, status, code);
      }
      throw new GinkgoApiError("unknown" /* UNKNOWN */, message, status, code);
    }
    if (resp.text === "" || resp.text === void 0 || resp.text === null) {
      return void 0;
    }
    return resp.json;
  }
  async health() {
    return this.request("GET", "/health");
  }
  async isConnected() {
    try {
      const h = await this.health();
      return h.status === "ok";
    } catch (e) {
      return false;
    }
  }
  async getStatus() {
    return this.request("GET", "/status");
  }
  async getSources() {
    return this.request("GET", "/sources");
  }
  async getRepositories() {
    return this.request("GET", "/repositories");
  }
  async createSource(path, name, repoPaths, schedule = "daily", excludes) {
    const body = { path, name, schedule, repo_paths: repoPaths };
    if (excludes && excludes.length > 0) {
      body.excludes = excludes;
    }
    return this.request("POST", "/sources", body);
  }
  async findSourceByPath(vaultPath) {
    const sources = await this.getSources();
    const normalized = vaultPath.replace(/\\/g, "/").toLowerCase();
    for (const s of sources) {
      if (s.path.replace(/\\/g, "/").toLowerCase() === normalized) {
        return s;
      }
    }
    return null;
  }
  async ensureSourceExists(vaultPath, name, repoPaths, excludes) {
    const existing = await this.findSourceByPath(vaultPath);
    if (existing) {
      const updatePayload = { repo_paths: repoPaths };
      if (excludes)
        updatePayload.excludes = excludes;
      await this.updateSource(existing.id, updatePayload);
      return await this.getSourceById(existing.id);
    }
    return await this.createSource(vaultPath, name, repoPaths, "hourly", excludes);
  }
  async getSourceById(id) {
    try {
      return await this.request("GET", `/sources/${id}`);
    } catch (e) {
      return null;
    }
  }
  async updateSource(id, updates) {
    await this.request("PUT", `/sources/${id}`, updates);
  }
  async triggerBackup(sourceId, message) {
    return this.request("POST", "/backup/run", {
      source_id: sourceId,
      message: message != null ? message : ""
    });
  }
  async getProgress(sourceId) {
    const path = sourceId ? `/backup/progress?source_id=${sourceId}` : "/backup/progress";
    return this.request("GET", path);
  }
  async getBackupState() {
    return this.request("GET", "/backup/state");
  }
  async cancelBackup(sourceId) {
    const path = sourceId ? `/backup/cancel?source_id=${sourceId}` : "/backup/cancel";
    await this.request("POST", path);
  }
  async stagingPush(req) {
    var _a;
    return this.request("POST", "/staging/push", {
      ...req,
      trigger: (_a = req.trigger) != null ? _a : "api"
    });
  }
  async getStagingSession(sessionId) {
    return this.request("GET", `/staging/session?id=${sessionId}`);
  }
  async getSnapshots(sourceId, limit = 20, offset = 0) {
    return this.request(
      "GET",
      `/snapshots?source_id=${sourceId}&limit=${limit}&offset=${offset}`
    );
  }
  async getFileHistory(sourceId, filePath, repoPath) {
    const encoded = encodeURIComponent(filePath);
    let url = `/history?source_id=${sourceId}&path=${encoded}`;
    if (repoPath) {
      url += `&repo=${encodeURIComponent(repoPath)}`;
    }
    return this.request("GET", url);
  }
  async getFileContent(sourceId, filePath, snapshotTime, repoPath) {
    const encoded = encodeURIComponent(filePath);
    let url = `/history/content?source_id=${sourceId}&path=${encoded}&snapshot=${snapshotTime}`;
    if (repoPath) {
      url += `&repo=${encodeURIComponent(repoPath)}`;
    }
    return this.request("GET", url);
  }
  async getFileDiff(sourceId, filePath, oldSnapshot, newSnapshot, repoPath) {
    const encoded = encodeURIComponent(filePath);
    let url = `/history/diff?source_id=${sourceId}&path=${encoded}&old_snapshot=${oldSnapshot}&new_snapshot=${newSnapshot}`;
    if (repoPath) {
      url += `&repo=${encodeURIComponent(repoPath)}`;
    }
    return this.request("GET", url);
  }
  async restoreFile(sourceId, filePath, snapshotTime, destPath, repoPath) {
    const body = {
      source_id: sourceId,
      path: filePath,
      snapshot: snapshotTime
    };
    if (destPath) {
      body.dest = destPath;
    }
    if (repoPath) {
      body.repo = repoPath;
    }
    return this.request("POST", "/history/restore", body);
  }
  async browseDirectory(sourceId, dirPath, snapshotTime, limit = 100, offset = 0) {
    const params = new URLSearchParams({
      source_id: String(sourceId),
      dir: dirPath,
      limit: String(limit),
      offset: String(offset)
    });
    if (snapshotTime !== void 0) {
      params.set("snapshot", String(snapshotTime));
    }
    return this.request("GET", `/files?${params.toString()}`);
  }
};

// src/settings-tab.ts
var import_obsidian2 = require("obsidian");
var RepoMultiSelectModal = class extends import_obsidian2.Modal {
  constructor(app, repos, preselectedPaths, onConfirm) {
    super(app);
    this.selected = /* @__PURE__ */ new Set();
    this.repos = repos;
    this.onConfirm = onConfirm;
    for (const repo of repos) {
      if (preselectedPaths.some((p) => p.replace(/\\/g, "/") === repo.path.replace(/\\/g, "/"))) {
        this.selected.add(repo.id);
      }
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("ginkgo-repo-select-modal");
    const headerEl = contentEl.createEl("div", { cls: "ginkgo-repo-header" });
    headerEl.createEl("h2", { text: "\u914D\u7F6E\u5907\u4EFD\u6E90" });
    this.countEl = headerEl.createEl("span", { cls: "ginkgo-repo-count", text: `\u5DF2\u9009 ${this.selected.size} \u4E2A` });
    this.listEl = contentEl.createEl("div", { cls: "ginkgo-repo-list" });
    this.renderList();
    const footerEl = contentEl.createEl("div", { cls: "ginkgo-modal-footer" });
    this.confirmBtn = footerEl.createEl("button", {
      cls: "ginkgo-btn-restore",
      text: "\u786E\u8BA4\u914D\u7F6E"
    });
    this.confirmBtn.disabled = this.selected.size === 0;
    this.confirmBtn.addEventListener("click", () => {
      const selectedRepos = this.repos.filter((r) => this.selected.has(r.id));
      if (selectedRepos.length === 0)
        return;
      this.onConfirm(selectedRepos);
      this.close();
    });
    const cancelBtn = footerEl.createEl("button", { text: "\u53D6\u6D88", cls: "ginkgo-close-btn" });
    cancelBtn.addEventListener("click", () => this.close());
  }
  updateSelection() {
    this.countEl.setText(`\u5DF2\u9009 ${this.selected.size} \u4E2A`);
    this.confirmBtn.disabled = this.selected.size === 0;
  }
  renderList() {
    this.listEl.empty();
    for (const repo of this.repos) {
      const isSelected = this.selected.has(repo.id);
      const itemEl = this.listEl.createEl("div", {
        cls: `ginkgo-repo-card ${isSelected ? "is-selected" : ""}`
      });
      itemEl.addEventListener("click", () => {
        if (this.selected.has(repo.id)) {
          this.selected.delete(repo.id);
        } else {
          this.selected.add(repo.id);
        }
        this.renderList();
        this.updateSelection();
      });
      const checkEl = itemEl.createEl("div", { cls: "ginkgo-repo-check" });
      const checkbox = checkEl.createEl("input", { type: "checkbox" });
      checkbox.checked = isSelected;
      checkbox.addEventListener("click", (e) => {
        e.stopPropagation();
        if (checkbox.checked) {
          this.selected.add(repo.id);
        } else {
          this.selected.delete(repo.id);
        }
        this.renderList();
        this.updateSelection();
      });
      const bodyEl = itemEl.createEl("div", { cls: "ginkgo-repo-body" });
      const nameRow = bodyEl.createEl("div", { cls: "ginkgo-repo-name-row" });
      nameRow.createEl("span", { cls: "ginkgo-repo-name", text: repo.display_name || repo.path });
      const badgesEl = nameRow.createEl("span", { cls: "ginkgo-repo-badges" });
      if (repo.type === "cloud" || repo.type === "s3") {
        badgesEl.createEl("span", { cls: "ginkgo-repo-badge ginkgo-badge-cloud", text: "\u4E91\u7AEF" });
      } else if (repo.type === "webdav") {
        badgesEl.createEl("span", { cls: "ginkgo-repo-badge ginkgo-badge-cloud", text: "WebDAV" });
      } else {
        badgesEl.createEl("span", { cls: "ginkgo-repo-badge ginkgo-badge-local", text: "\u672C\u5730" });
      }
      if (repo.encrypted) {
        badgesEl.createEl("span", { cls: "ginkgo-repo-badge ginkgo-badge-encrypted", text: "\u52A0\u5BC6" });
      }
      bodyEl.createEl("div", { cls: "ginkgo-repo-path", text: repo.path });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var GinkgoBackupSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const bannerEl = containerEl.createEl("div", { cls: "ginkgo-settings-banner" });
    const bannerLeft = bannerEl.createEl("div", { cls: "ginkgo-settings-banner-left" });
    const iconEl = bannerLeft.createEl("span", { cls: "ginkgo-settings-banner-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "leaf");
    const titleEl = bannerLeft.createEl("div", { cls: "ginkgo-settings-banner-text" });
    titleEl.createEl("div", { cls: "ginkgo-settings-banner-title", text: "Ginkgo Backup" });
    titleEl.createEl("div", { cls: "ginkgo-settings-banner-version", text: "\u94F6\u674F\u65F6\u5149\u5907\u4EFD \xB7 Obsidian \u63D2\u4EF6 v0.3.0" });
    const statusDot = bannerEl.createEl("div", { cls: "ginkgo-settings-banner-status" });
    this.checkBannerStatus(statusDot);
    this.renderConnectionSection(containerEl);
    this.renderAutoBackupSection(containerEl);
    this.renderFilterSection(containerEl);
    this.renderActionsSection(containerEl);
    this.renderHelpSection(containerEl);
  }
  renderConnectionSection(containerEl) {
    containerEl.createEl("h3", { text: "\u8FDE\u63A5" });
    const statusEl = containerEl.createEl("div", { cls: "ginkgo-settings-status" });
    this.checkAndDisplayStatus(statusEl);
    new import_obsidian2.Setting(containerEl).setName("API \u4E3B\u673A").setDesc("\u652F\u6301 IP\u3001\u57DF\u540D\u6216\u5B8C\u6574 URL\uFF08\u5982 https://ginkgo.example.com\uFF09").addText(
      (text) => text.setPlaceholder("127.0.0.1 \u6216 https://ginkgo.example.com").setValue(this.plugin.settings.apiHost).onChange(async (value) => {
        this.plugin.settings.apiHost = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API \u7AEF\u53E3").setDesc("API \u670D\u52A1\u7AEF\u53E3\uFF08\u9ED8\u8BA4 9275\uFF09").addText(
      (text) => text.setPlaceholder("9275").setValue(String(this.plugin.settings.apiPort)).onChange(async (value) => {
        const port = parseInt(value, 10);
        if (!isNaN(port) && port > 0 && port < 65536) {
          this.plugin.settings.apiPort = port;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API Token").setDesc("\u5728 Ginkgo Backup \u684C\u9762\u5E94\u7528\u7684\u8BBE\u7F6E\u9875\u9762\u83B7\u53D6").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian2.Setting(containerEl).setName("Vault \u6807\u8BC6\u7B26").setDesc("\u7559\u7A7A\u5219\u81EA\u52A8\u68C0\u6D4B\u3002\u591A\u8BBE\u5907\u540C\u540D Vault \u65F6\u9700\u8BBE\u7F6E\u552F\u4E00\u6807\u8BC6\uFF08\u5982 MyVault-iPhone\uFF09\uFF0C\u786E\u4FDD\u6BCF\u4E2A\u8BBE\u5907\u5BF9\u5E94\u72EC\u7ACB\u5907\u4EFD\u6E90").addText(
      (text) => text.setPlaceholder("\u81EA\u52A8\u68C0\u6D4B").setValue(this.plugin.settings.vaultIdentifier).onChange(async (value) => {
        this.plugin.settings.vaultIdentifier = value.trim();
        this.plugin.vaultPath = "";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5907\u4EFD\u6E90").setDesc(this.plugin.settings.sourceId > 0 ? `\u5DF2\u914D\u7F6E\uFF08ID: ${this.plugin.settings.sourceId}\uFF09` : "\u672A\u914D\u7F6E\uFF0C\u70B9\u51FB\u4E00\u952E\u914D\u7F6E\u9009\u62E9\u4ED3\u5E93").addButton(
      (button) => button.setButtonText(this.plugin.settings.sourceId > 0 ? "\u91CD\u65B0\u914D\u7F6E" : "\u4E00\u952E\u914D\u7F6E").setCta().onClick(async () => {
        await this.showRepoSelector();
      })
    ).addText(
      (text) => text.setPlaceholder("ID").setValue(String(this.plugin.settings.sourceId)).onChange(async (value) => {
        const id = parseInt(value, 10);
        if (!isNaN(id) && id >= 0) {
          this.plugin.settings.sourceId = id;
          this.plugin.vaultSourceId = id;
          await this.plugin.saveSettings();
        }
      })
    );
  }
  renderAutoBackupSection(containerEl) {
    containerEl.createEl("h3", { text: "\u5907\u4EFD\u7B56\u7565" });
    new import_obsidian2.Setting(containerEl).setName("\u5373\u65F6\u63A8\u9001").setDesc("\u6587\u4EF6\u4FDD\u5B58\u540E\u81EA\u52A8\u63A8\u9001\u5230\u6682\u5B58\u533A\uFF08\u63A8\u8350\uFF0C\u5373\u65F6\u5B8C\u6210\uFF0C\u540E\u53F0\u5907\u4EFD\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stagingPushOnSave).onChange(async (value) => {
        this.plugin.settings.stagingPushOnSave = value;
        if (value) {
          this.plugin.settings.autoBackupOnSave = false;
        }
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5168\u91CF\u5907\u4EFD").setDesc("\u6587\u4EF6\u4FDD\u5B58\u540E\u89E6\u53D1\u5168\u91CF\u5907\u4EFD\uFF08\u8F83\u6162\uFF0C\u4E0E\u5373\u65F6\u63A8\u9001\u4E92\u65A5\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoBackupOnSave).setDisabled(this.plugin.settings.stagingPushOnSave).onChange(async (value) => {
        this.plugin.settings.autoBackupOnSave = value;
        if (value) {
          this.plugin.settings.stagingPushOnSave = false;
        }
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u9632\u6296\u5EF6\u8FDF").setDesc("\u6587\u4EF6\u4FDD\u5B58\u540E\u7B49\u5F85\u591A\u4E45\u518D\u89E6\u53D1\u63A8\u9001\uFF08\u6BEB\u79D2\uFF09").addSlider(
      (slider) => slider.setLimits(5e3, 12e4, 5e3).setValue(this.plugin.settings.autoBackupDebounceMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.autoBackupDebounceMs = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u76D1\u63A7\u6587\u4EF6\u7C7B\u578B").setDesc("\u5373\u65F6\u63A8\u9001\u7684\u6587\u4EF6\u6269\u5C55\u540D\uFF0C\u9017\u53F7\u6216\u6362\u884C\u5206\u9694\uFF08\u5982 md, canvas, base\uFF09\u3002\u5176\u4ED6\u6587\u4EF6\u7531\u515C\u5E95\u5907\u4EFD\u8986\u76D6").addTextArea(
      (text) => text.setPlaceholder("md, canvas, base").setValue(this.plugin.settings.watchExtensions.join(", ")).onChange(async (value) => {
        this.plugin.settings.watchExtensions = value.split(/[,\n]/).map((s) => s.trim().replace(/^\./, "")).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
  renderFilterSection(containerEl) {
    containerEl.createEl("h3", { text: "\u8FC7\u6EE4\u4E0E\u663E\u793A" });
    new import_obsidian2.Setting(containerEl).setName("\u6392\u9664\u8DEF\u5F84\u5217\u8868").setDesc("\u4E0D\u5907\u4EFD\u7684\u8DEF\u5F84\u524D\u7F00\uFF0C\u6BCF\u884C\u4E00\u4E2A\uFF08\u5982 .obsidian, .trash\uFF09").addTextArea(
      (text) => text.setPlaceholder(".obsidian\n.trash\n.DS_Store").setValue(this.plugin.settings.excludePaths.join("\n")).onChange(async (value) => {
        this.plugin.settings.excludePaths = value.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u663E\u793A\u72B6\u6001\u680F").setDesc("\u5728\u72B6\u6001\u680F\u663E\u793A\u5907\u4EFD\u72B6\u6001").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStatusBar).onChange(async (value) => {
        this.plugin.settings.showStatusBar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5237\u65B0\u95F4\u9694").setDesc("\u72B6\u6001\u680F\u5237\u65B0\u95F4\u9694\uFF08\u79D2\uFF09").addSlider(
      (slider) => slider.setLimits(10, 300, 10).setValue(this.plugin.settings.refreshInterval).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.refreshInterval = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderActionsSection(containerEl) {
    containerEl.createEl("h3", { text: "\u5FEB\u6377\u64CD\u4F5C" });
    new import_obsidian2.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u9A8C\u8BC1\u4E0E Ginkgo Backup \u7684\u8FDE\u63A5").addButton(
      (button) => button.setButtonText("\u6D4B\u8BD5").onClick(async () => {
        button.setDisabled(true);
        try {
          const health = await this.plugin.client.health();
          new import_obsidian2.Notice(`Ginkgo: \u5DF2\u8FDE\u63A5 (v${health.version})`);
        } catch (e) {
          new import_obsidian2.Notice("Ginkgo: \u8FDE\u63A5\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u4E3B\u673A\u3001\u7AEF\u53E3\u548C Token");
        }
        button.setDisabled(false);
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u7ACB\u5373\u5907\u4EFD").setDesc("\u89E6\u53D1\u5168\u91CF\u5907\u4EFD").addButton(
      (button) => button.setButtonText("\u5907\u4EFD").onClick(() => this.plugin.backupVault())
    );
    new import_obsidian2.Setting(containerEl).setName("\u6253\u5F00\u5E94\u7528").setDesc("\u5728\u6D4F\u89C8\u5668\u4E2D\u6253\u5F00 Ginkgo Backup").addButton(
      (button) => button.setButtonText("\u6253\u5F00").onClick(() => this.plugin.openGinkgoApp())
    );
  }
  renderHelpSection(containerEl) {
    containerEl.createEl("h3", { text: "\u5E2E\u52A9" });
    const helpEl = containerEl.createEl("div", { cls: "ginkgo-settings-help" });
    helpEl.createEl("p", {
      text: "\u786E\u4FDD Ginkgo Backup \u684C\u9762\u5E94\u7528\u6B63\u5728\u8FD0\u884C\uFF0C\u5E76\u4E14\u5F53\u524D Vault \u5DF2\u6DFB\u52A0\u5230\u5907\u4EFD\u6E90\u3002"
    });
    helpEl.createEl("p", {
      text: "\u4F7F\u7528\u547D\u4EE4\u9762\u677F\uFF08Ctrl/Cmd + P\uFF09\u641C\u7D22 Ginkgo \u67E5\u770B\u6240\u6709\u53EF\u7528\u547D\u4EE4\u3002"
    });
    helpEl.createEl("p", {
      text: "\u5373\u65F6\u63A8\u9001\u6A21\u5F0F\uFF1A\u7B14\u8BB0\u4FDD\u5B58\u540E\u5373\u65F6\u63A8\u9001\u5230\u6682\u5B58\u533A\uFF0C\u540E\u53F0\u81EA\u52A8\u5B8C\u6210\u5907\u4EFD\uFF0C\u4E0D\u963B\u585E\u7F16\u8F91\u3002\u56FE\u7247\u7B49\u9644\u4EF6\u7531\u515C\u5E95\u5907\u4EFD\u8986\u76D6\u3002"
    });
  }
  async showRepoSelector() {
    try {
      const repos = await this.plugin.client.getRepositories();
      if (repos.length === 0) {
        new import_obsidian2.Notice("Ginkgo: \u6CA1\u6709\u53EF\u7528\u7684\u5907\u4EFD\u4ED3\u5E93\uFF0C\u8BF7\u5148\u5728 Ginkgo Backup \u4E2D\u521B\u5EFA\u4ED3\u5E93");
        return;
      }
      let preselectedPaths = [];
      if (this.plugin.vaultSourceId > 0) {
        try {
          const source = await this.plugin.client.getSourceById(this.plugin.vaultSourceId);
          if (source)
            preselectedPaths = source.repo_paths || [];
        } catch (e) {
        }
      }
      const modal = new RepoMultiSelectModal(this.app, repos, preselectedPaths, async (selectedRepos) => {
        const repoPaths = selectedRepos.map((r) => r.path);
        const names = selectedRepos.map((r) => r.display_name || r.path).join(", ");
        new import_obsidian2.Notice(`Ginkgo: \u5DF2\u9009\u62E9\u4ED3\u5E93 ${names}`);
        await this.plugin.setupSource(repoPaths);
        this.display();
      });
      modal.open();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      new import_obsidian2.Notice(`Ginkgo: \u83B7\u53D6\u4ED3\u5E93\u5217\u8868\u5931\u8D25 \u2014 ${msg}`);
    }
  }
  async checkBannerStatus(el) {
    try {
      const connected = await this.plugin.client.isConnected();
      if (connected) {
        el.addClass("ginkgo-banner-connected");
        el.setAttribute("aria-label", "\u5DF2\u8FDE\u63A5");
      } else {
        el.addClass("ginkgo-banner-disconnected");
        el.setAttribute("aria-label", "\u672A\u8FDE\u63A5");
      }
    } catch (e) {
      el.addClass("ginkgo-banner-disconnected");
    }
  }
  async checkAndDisplayStatus(el) {
    if (!el)
      return;
    el.empty();
    el.removeClass("ginkgo-status-ok", "ginkgo-status-err", "ginkgo-status-warn");
    try {
      const connected = await this.plugin.client.isConnected();
      if (!connected) {
        el.setText("\u274C \u672A\u8FDE\u63A5\u5230 Ginkgo Backup");
        el.addClass("ginkgo-status-err");
        return;
      }
      const vaultPath = this.plugin.getVaultPath();
      const source = vaultPath ? await this.plugin.client.findSourceByPath(vaultPath) : null;
      if (source) {
        el.setText("\u2705 \u5DF2\u8FDE\u63A5 \u2014 \u5F53\u524D Vault \u5DF2\u914D\u7F6E\u5907\u4EFD");
        el.addClass("ginkgo-status-ok");
      } else {
        el.setText("\u26A0\uFE0F \u5DF2\u8FDE\u63A5 \u2014 \u5F53\u524D Vault \u672A\u914D\u7F6E\u5907\u4EFD");
        el.addClass("ginkgo-status-warn");
      }
    } catch (e) {
      el.setText("\u274C \u8FDE\u63A5\u9519\u8BEF");
      el.addClass("ginkgo-status-err");
    }
  }
};

// src/timeline-view.ts
var import_obsidian3 = require("obsidian");
var TIMELINE_VIEW_TYPE = "ginkgo-backup-timeline";
var FileHistoryView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.snapshots = [];
    this.plugin = plugin;
  }
  getViewType() {
    return TIMELINE_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u5907\u4EFD\u65F6\u95F4\u7EBF";
  }
  getIcon() {
    return "hard-drive";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ginkgo-timeline-container");
    const headerEl = container.createEl("div", { cls: "ginkgo-timeline-header" });
    const h3 = headerEl.createEl("h3");
    const iconSpan = h3.createSpan({ cls: "ginkgo-timeline-icon" });
    (0, import_obsidian3.setIcon)(iconSpan, "hard-drive");
    iconSpan.style.marginRight = "8px";
    h3.createSpan({ text: "\u5907\u4EFD\u65F6\u95F4\u7EBF" });
    const refreshBtn = headerEl.createEl("button", { text: "\u5237\u65B0", cls: "ginkgo-refresh-btn" });
    refreshBtn.addEventListener("click", () => this.onOpen());
    const backupBtn = headerEl.createEl("button", { text: "\u7ACB\u5373\u5907\u4EFD", cls: "ginkgo-backup-btn" });
    backupBtn.addEventListener("click", () => this.plugin.backupVault());
    if (this.plugin.vaultSourceId === 0) {
      const emptyEl = container.createEl("div", { cls: "ginkgo-empty-state" });
      const iconEl = emptyEl.createEl("div", { cls: "ginkgo-empty-icon" });
      (0, import_obsidian3.setIcon)(iconEl, "hard-drive");
      emptyEl.createEl("div", { cls: "ginkgo-empty-title", text: "\u5C1A\u672A\u914D\u7F6E\u5907\u4EFD\u6E90" });
      emptyEl.createEl("div", { cls: "ginkgo-empty-desc", text: "\u4F7F\u7528\u547D\u4EE4 Ginkgo: \u914D\u7F6E\u5907\u4EFD\u6E90 \u6765\u5F00\u59CB" });
      return;
    }
    const loadingEl = container.createEl("div", { cls: "ginkgo-loading" });
    loadingEl.createEl("span", { text: "\u52A0\u8F7D\u4E2D..." });
    try {
      const result = await this.plugin.client.getSnapshots(this.plugin.vaultSourceId, 50);
      this.snapshots = result.items;
      loadingEl.remove();
      this.renderTimeline(container);
    } catch (err) {
      loadingEl.remove();
      const msg = err instanceof Error ? err.message : String(err);
      container.createEl("p", { text: `\u52A0\u8F7D\u5931\u8D25: ${msg}`, cls: "ginkgo-error" });
    }
  }
  renderTimeline(container) {
    container.findAll(".ginkgo-timeline-summary, .ginkgo-timeline-list, .ginkgo-empty-state").forEach((el) => el.remove());
    if (this.snapshots.length === 0) {
      const emptyEl = container.createEl("div", { cls: "ginkgo-empty-state" });
      const iconEl = emptyEl.createEl("div", { cls: "ginkgo-empty-icon" });
      (0, import_obsidian3.setIcon)(iconEl, "archive");
      emptyEl.createEl("div", { cls: "ginkgo-empty-title", text: "\u6682\u65E0\u5907\u4EFD\u8BB0\u5F55" });
      emptyEl.createEl("div", { cls: "ginkgo-empty-desc", text: "\u70B9\u51FB\u300C\u7ACB\u5373\u5907\u4EFD\u300D\u521B\u5EFA\u7B2C\u4E00\u4E2A\u5FEB\u7167" });
      return;
    }
    this.renderSummary(container);
    const grouped = this.groupByDate(this.snapshots);
    const listEl = container.createEl("div", { cls: "ginkgo-timeline-list" });
    for (const [date, daySnapshots] of Object.entries(grouped)) {
      const dateEl = listEl.createEl("div", { cls: "ginkgo-date-group" });
      dateEl.createEl("h4", { text: date });
      for (const snap of daySnapshots) {
        const itemEl = dateEl.createEl("div", { cls: "ginkgo-timeline-item" });
        const trackEl = itemEl.createEl("div", { cls: "ginkgo-timeline-track" });
        const dotCls = this.getDotClass(snap, daySnapshots);
        trackEl.createEl("div", { cls: dotCls });
        const cardEl = itemEl.createEl("div", { cls: "ginkgo-timeline-card" });
        cardEl.addEventListener("click", () => this.openSnapshotDetail(snap));
        const time = new Date(snap.timestamp / 1e3);
        cardEl.createEl("div", {
          cls: "ginkgo-card-time",
          text: time.toLocaleTimeString(void 0, { hour: "2-digit", minute: "2-digit" })
        });
        const metaEl = cardEl.createEl("div", { cls: "ginkgo-card-meta" });
        metaEl.createEl("span", { text: `${snap.file_count} \u6587\u4EF6` });
        metaEl.createEl("span", { text: this.plugin.formatBytes(snap.total_size) });
        if (snap.new_files > 0) {
          metaEl.createEl("span", {
            text: `+${snap.new_files}`,
            cls: "ginkgo-meta-new"
          });
        }
        if (snap.changed_files > 0) {
          metaEl.createEl("span", {
            text: `~${snap.changed_files}`,
            cls: "ginkgo-meta-changed"
          });
        }
        if (snap.tags && snap.tags.length > 0) {
          const tagsEl = cardEl.createEl("div", { cls: "ginkgo-card-tags" });
          for (const tag of snap.tags) {
            tagsEl.createEl("span", {
              text: tag,
              cls: `ginkgo-tag ginkgo-tag-${tag}`
            });
          }
        }
        if (snap.status !== "complete") {
          cardEl.createEl("span", {
            text: snap.status,
            cls: "ginkgo-badge-status"
          });
        }
      }
    }
  }
  renderSummary(container) {
    const summaryEl = container.createEl("div", { cls: "ginkgo-timeline-summary" });
    const totalSize = this.snapshots.reduce((sum, s) => sum + s.total_size, 0);
    const latestSnap = this.snapshots[0];
    const lastTime = latestSnap ? new Date(latestSnap.timestamp / 1e3).toLocaleTimeString(void 0, { hour: "2-digit", minute: "2-digit" }) : "-";
    const items = [
      { value: String(this.snapshots.length), label: "\u5FEB\u7167" },
      { value: this.plugin.formatBytes(totalSize), label: "\u603B\u5927\u5C0F" },
      { value: lastTime, label: "\u6700\u8FD1\u5907\u4EFD" }
    ];
    for (const item of items) {
      const itemEl = summaryEl.createEl("div", { cls: "ginkgo-summary-item" });
      itemEl.createEl("div", { cls: "ginkgo-summary-value", text: item.value });
      itemEl.createEl("div", { cls: "ginkgo-summary-label", text: item.label });
    }
  }
  getDotClass(snap, daySnapshots) {
    const parts = ["ginkgo-dot"];
    if (snap === daySnapshots[0]) {
      parts.push("ginkgo-dot-latest");
    } else if (snap.status !== "complete") {
      parts.push("ginkgo-dot-error");
    } else {
      parts.push("ginkgo-dot-success");
    }
    return parts.join(" ");
  }
  groupByDate(snapshots) {
    const grouped = {};
    for (const snap of snapshots) {
      const date = new Date(snap.timestamp / 1e3).toLocaleDateString(void 0, {
        year: "numeric",
        month: "long",
        day: "numeric"
      });
      if (!grouped[date])
        grouped[date] = [];
      grouped[date].push(snap);
    }
    return grouped;
  }
  openSnapshotDetail(snap) {
    new SnapshotDetailModal(this.app, this.plugin, snap).open();
  }
  async onClose() {
  }
};
var SnapshotDetailModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, snap) {
    super(app);
    this.plugin = plugin;
    this.snap = snap;
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.addClass("ginkgo-snapshot-modal");
    const time = new Date(this.snap.timestamp / 1e3);
    const headerEl = contentEl.createEl("div", { cls: "ginkgo-snap-header" });
    const titleEl = headerEl.createEl("div", { cls: "ginkgo-snap-title" });
    const iconSpan = titleEl.createSpan({ cls: "ginkgo-snap-title-icon" });
    (0, import_obsidian3.setIcon)(iconSpan, "camera");
    titleEl.createSpan({ text: `\u5FEB\u7167 ${time.toLocaleString()}` });
    const statsEl = contentEl.createEl("div", { cls: "ginkgo-snap-stats" });
    const statItems = [
      { icon: "files", label: "\u6587\u4EF6", value: `${this.snap.file_count} \u6587\u4EF6 \xB7 ${this.snap.dir_count} \u76EE\u5F55` },
      { icon: "hard-drive", label: "\u5927\u5C0F", value: this.plugin.formatBytes(this.snap.total_size) }
    ];
    if (this.snap.new_files > 0) {
      statItems.push({ icon: "plus-circle", label: "\u65B0\u589E", value: `${this.snap.new_files} \u6587\u4EF6`, cls: "ginkgo-stat-new" });
    }
    if (this.snap.changed_files > 0) {
      statItems.push({ icon: "refresh-cw", label: "\u4FEE\u6539", value: `${this.snap.changed_files} \u6587\u4EF6`, cls: "ginkgo-stat-changed" });
    }
    if (this.snap.deleted_count > 0) {
      statItems.push({ icon: "minus-circle", label: "\u5220\u9664", value: `${this.snap.deleted_count} \u6587\u4EF6`, cls: "ginkgo-stat-deleted" });
    }
    if (this.snap.duration_ms > 0) {
      const sec = Math.round(this.snap.duration_ms / 1e3);
      statItems.push({ icon: "timer", label: "\u8017\u65F6", value: sec >= 60 ? `${Math.floor(sec / 60)}m${sec % 60}s` : `${sec}s` });
    }
    for (const item of statItems) {
      const statEl = statsEl.createEl("div", { cls: `ginkgo-snap-stat ${(_a = item.cls) != null ? _a : ""}` });
      const iconSpan2 = statEl.createEl("span", { cls: "ginkgo-snap-stat-icon" });
      (0, import_obsidian3.setIcon)(iconSpan2, item.icon);
      const textEl = statEl.createEl("div", { cls: "ginkgo-snap-stat-text" });
      textEl.createEl("span", { cls: "ginkgo-snap-stat-label", text: item.label });
      textEl.createEl("span", { cls: "ginkgo-snap-stat-value", text: item.value });
    }
    const fileSectionEl = contentEl.createEl("div", { cls: "ginkgo-snap-file-section" });
    const fileHeaderEl = fileSectionEl.createEl("div", { cls: "ginkgo-snap-file-header" });
    fileHeaderEl.createEl("span", { text: "\u6587\u4EF6\u5217\u8868" });
    const loadingEl = fileHeaderEl.createEl("span", { cls: "ginkgo-snap-loading", text: "\u52A0\u8F7D\u4E2D..." });
    const fileListEl = fileSectionEl.createEl("div", { cls: "ginkgo-snap-file-list" });
    this.loadFiles(fileListEl, loadingEl);
  }
  async loadFiles(listEl, loadingEl) {
    var _a;
    try {
      const result = await this.plugin.client.browseDirectory(
        this.plugin.vaultSourceId,
        "",
        this.snap.timestamp,
        200,
        0
      );
      loadingEl.remove();
      const entries = (_a = result.entries) != null ? _a : [];
      if (entries.length === 0) {
        listEl.createEl("div", { cls: "ginkgo-snap-empty", text: "\u6B64\u5FEB\u7167\u65E0\u6587\u4EF6" });
        return;
      }
      const dirs = entries.filter((e) => e.type === "dir");
      const files = entries.filter((e) => e.type !== "dir");
      const sorted = [...dirs, ...files];
      for (const entry of sorted) {
        const rowEl = listEl.createEl("div", {
          cls: `ginkgo-snap-file-row ${entry.is_deleted ? "is-deleted" : ""} ${entry.type === "dir" ? "is-dir" : "is-file"}`
        });
        const iconCls = entry.type === "dir" ? "folder" : this.getFileIcon(entry.name);
        const iconEl = rowEl.createEl("span", { cls: "ginkgo-snap-file-icon" });
        (0, import_obsidian3.setIcon)(iconEl, iconCls);
        rowEl.createEl("span", { cls: "ginkgo-snap-file-name", text: entry.name });
        if (entry.is_deleted) {
          rowEl.createEl("span", { cls: "ginkgo-snap-file-deleted", text: "\u5DF2\u5220\u9664" });
        }
        const rightEl = rowEl.createEl("span", { cls: "ginkgo-snap-file-right" });
        if (entry.type !== "dir") {
          rightEl.createEl("span", { cls: "ginkgo-snap-file-size", text: this.plugin.formatBytes(entry.size) });
        } else if (entry.file_count > 0) {
          rightEl.createEl("span", { cls: "ginkgo-snap-file-count", text: `${entry.file_count} \u6587\u4EF6` });
        }
        if (entry.type !== "dir") {
          rowEl.addEventListener("click", () => {
            if (this.plugin.vaultSourceId > 0) {
              const filePath = entry.path || entry.name;
              this.close();
              this.plugin.showFileHistoryByPath(filePath);
            }
          });
        }
      }
      if (result.has_more) {
        listEl.createEl("div", { cls: "ginkgo-snap-file-more", text: `\u8FD8\u6709\u66F4\u591A\u6587\u4EF6\uFF08\u5171 ${result.total} \u9879\uFF09` });
      }
    } catch (err) {
      loadingEl.remove();
      const msg = err instanceof Error ? err.message : String(err);
      listEl.createEl("div", { cls: "ginkgo-error", text: `\u52A0\u8F7D\u5931\u8D25: ${msg}` });
    }
  }
  getFileIcon(name) {
    var _a, _b, _c;
    const ext = (_b = (_a = name.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
    const iconMap = {
      md: "file-text",
      txt: "file-text",
      json: "file-json",
      css: "file-code",
      js: "file-code",
      ts: "file-code",
      png: "image",
      jpg: "image",
      jpeg: "image",
      gif: "image",
      svg: "image",
      webp: "image",
      pdf: "file-text",
      canvas: "layout-dashboard"
    };
    return (_c = iconMap[ext]) != null ? _c : "file";
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var GinkgoBackupPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.vaultSourceId = 0;
    this.vaultRepoPath = "";
    this.vaultPath = "";
    this.connected = false;
    this.consecutiveFailures = 0;
    this.pendingModifiedFiles = /* @__PURE__ */ new Set();
    this.lastPushedHashes = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.client = new GinkgoBackupClient(
      this.settings.apiHost,
      this.settings.apiPort,
      this.settings.apiToken
    );
    this.registerView(TIMELINE_VIEW_TYPE, (leaf) => new FileHistoryView(leaf, this));
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("ginkgo-status-bar");
    this.statusBarItem.addEventListener("click", (e) => this.showStatusBarMenu(e));
    this.updateStatusBar("connecting");
    this.applyStatusBarVisibility();
    this.addSettingTab(new GinkgoBackupSettingTab(this.app, this));
    this.addRibbonIcon("hard-drive", "Ginkgo Backup", () => this.openTimeline());
    this.addCommands();
    this.addFileContextMenu();
    this.addEditorContextMenu();
    this.startStatusRefresh();
    await this.loadHashCache();
    this.setupAutoBackup();
    this.debouncedSavePending = (0, import_obsidian6.debounce)(() => this.savePendingCache(), 5e3);
    await this.loadPendingCache();
    if (this.pendingModifiedFiles.size > 0) {
      new import_obsidian6.Notice(`Ginkgo: \u6062\u590D ${this.pendingModifiedFiles.size} \u4E2A\u5F85\u63A8\u9001\u6587\u4EF6`, 5e3);
    }
    this.initializeConnection();
  }
  onunload() {
    if (this.refreshTimer)
      window.clearInterval(this.refreshTimer);
    if (this.progressTimer)
      window.clearInterval(this.progressTimer);
    this.app.workspace.detachLeavesOfType(TIMELINE_VIEW_TYPE);
    this.saveHashCache();
    if (this.pendingModifiedFiles.size > 0 && this.connected && this.vaultSourceId > 0) {
      this.stagingPushPendingFiles();
    } else if (this.pendingModifiedFiles.size > 0) {
      this.savePendingCache();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.client.updateConfig(
      this.settings.apiHost,
      this.settings.apiPort,
      this.settings.apiToken
    );
    this.setupAutoBackup();
    this.applyStatusBarVisibility();
  }
  applyStatusBarVisibility() {
    this.statusBarItem.style.display = this.settings.showStatusBar ? "" : "none";
  }
  addCommands() {
    this.addCommand({
      id: "ginkgo-backup-now",
      name: "\u7ACB\u5373\u5907\u4EFD",
      callback: () => this.backupVault()
    });
    this.addCommand({
      id: "ginkgo-staging-push",
      name: "\u63A8\u9001\u5F53\u524D\u6587\u4EF6\u53D8\u66F4 (Staging Push)",
      editorCallback: (_editor, view) => {
        if (view.file)
          this.stagingPushFile(view.file);
      }
    });
    this.addCommand({
      id: "ginkgo-check-status",
      name: "\u68C0\u67E5\u5907\u4EFD\u72B6\u6001",
      callback: () => this.checkStatus()
    });
    this.addCommand({
      id: "ginkgo-setup-source",
      name: "\u914D\u7F6E\u5907\u4EFD\u6E90",
      callback: () => this.setupSource()
    });
    this.addCommand({
      id: "ginkgo-timeline",
      name: "\u6253\u5F00\u5907\u4EFD\u65F6\u95F4\u7EBF",
      callback: () => this.openTimeline()
    });
    this.addCommand({
      id: "ginkgo-file-history",
      name: "\u67E5\u770B\u5F53\u524D\u6587\u4EF6\u5386\u53F2\u7248\u672C",
      editorCallback: (_editor, view) => {
        if (view.file)
          this.showFileHistory(view.file);
      }
    });
    this.addCommand({
      id: "ginkgo-open-app",
      name: "\u6253\u5F00 Ginkgo Backup \u5E94\u7528",
      callback: () => this.openGinkgoApp()
    });
    this.addCommand({
      id: "ginkgo-cancel-backup",
      name: "\u53D6\u6D88\u5F53\u524D\u5907\u4EFD",
      callback: () => this.cancelBackup()
    });
  }
  addFileContextMenu() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian6.TFolder)
          return;
        menu.addItem((item) => {
          item.setTitle("\u5386\u53F2\u7248\u672C").setIcon("history").onClick(() => this.showFileHistory(file));
        });
      })
    );
  }
  addEditorContextMenu() {
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, _editor, view) => {
        if (view.file) {
          menu.addItem((item) => {
            item.setTitle("\u5386\u53F2\u7248\u672C").setIcon("history").onClick(() => this.showFileHistory(view.file));
          });
        }
      })
    );
  }
  async initializeConnection() {
    const connected = await this.client.isConnected();
    if (connected) {
      this.connected = true;
      this.consecutiveFailures = 0;
      await this.detectSourceId();
      this.updateStatusBar("connected");
    } else {
      this.connected = false;
      this.updateStatusBar("disconnected");
    }
  }
  async detectSourceId() {
    if (this.settings.sourceId > 0) {
      this.vaultSourceId = this.settings.sourceId;
      try {
        const source = await this.client.getSourceById(this.vaultSourceId);
        if (source && source.repo_paths.length > 0) {
          this.vaultRepoPath = source.repo_paths[0];
        }
      } catch (e) {
      }
      return;
    }
    const vaultPath = this.getVaultPath();
    if (!vaultPath)
      return;
    try {
      const source = await this.client.findSourceByPath(vaultPath);
      if (source) {
        this.vaultSourceId = source.id;
        this.vaultRepoPath = source.repo_paths.length > 0 ? source.repo_paths[0] : "";
        this.settings.sourceId = source.id;
        await this.saveSettings();
      }
    } catch (e) {
    }
  }
  getVaultPath() {
    if (this.vaultPath)
      return this.vaultPath;
    if (this.settings.vaultIdentifier) {
      this.vaultPath = this.settings.vaultIdentifier;
      return this.vaultPath;
    }
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian6.FileSystemAdapter) {
      this.vaultPath = adapter.getBasePath();
    } else {
      this.vaultPath = this.app.vault.getName();
    }
    return this.vaultPath;
  }
  isExcluded(filePath) {
    for (const pattern of this.settings.excludePaths) {
      if (filePath.startsWith(pattern) || filePath.includes("/" + pattern + "/") || filePath.includes("\\" + pattern + "\\")) {
        return true;
      }
    }
    return false;
  }
  isWatchedExtension(file) {
    return this.settings.watchExtensions.includes(file.extension);
  }
  async contentHash(str) {
    const data = new TextEncoder().encode(str);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  async hasContentChanged(file) {
    try {
      const content = await this.app.vault.read(file);
      const hash = await this.contentHash(content);
      const lastHash = this.lastPushedHashes.get(file.path);
      if (!lastHash) {
        this.lastPushedHashes.set(file.path, hash);
        return false;
      }
      if (hash === lastHash)
        return false;
      this.lastPushedHashes.set(file.path, hash);
      return true;
    } catch (e) {
      return true;
    }
  }
  async savePendingCache() {
    try {
      const data = Array.from(this.pendingModifiedFiles);
      await this.saveData({ ...this.settings, _pendingFiles: data });
    } catch (e) {
    }
  }
  async loadPendingCache() {
    var _a;
    try {
      const data = await this.loadData();
      const paths = (_a = data == null ? void 0 : data._pendingFiles) != null ? _a : [];
      if (Array.isArray(paths)) {
        for (const p of paths) {
          if (!this.isExcluded(p)) {
            this.pendingModifiedFiles.add(p);
          }
        }
      }
    } catch (e) {
    }
  }
  async clearPendingCache() {
    try {
      const data = await this.loadData();
      if (data == null ? void 0 : data._pendingFiles) {
        delete data._pendingFiles;
        await this.saveData(data);
      }
    } catch (e) {
    }
  }
  async saveHashCache() {
    try {
      const data = {};
      for (const [path, hash] of this.lastPushedHashes) {
        const file = this.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian6.TFile) {
          data[path] = hash;
        }
      }
      this.lastPushedHashes = new Map(Object.entries(data));
      const stored = await this.loadData();
      await this.saveData({ ...stored, _hashCache: data });
    } catch (e) {
    }
  }
  async loadHashCache() {
    var _a;
    try {
      const data = await this.loadData();
      const cache = (_a = data == null ? void 0 : data._hashCache) != null ? _a : {};
      for (const [path, hash] of Object.entries(cache)) {
        this.lastPushedHashes.set(path, hash);
      }
    } catch (e) {
    }
  }
  setupAutoBackup() {
    if (this.modifyEventRef) {
      this.app.vault.offref(this.modifyEventRef);
      this.modifyEventRef = void 0;
    }
    this.debouncedAutoBackup = (0, import_obsidian6.debounce)(
      async () => {
        if (!this.connected || this.vaultSourceId === 0)
          return;
        if (this.settings.stagingPushOnSave) {
          await this.stagingPushPendingFiles();
        } else if (this.settings.autoBackupOnSave) {
          await this.backupVault();
        }
      },
      this.settings.autoBackupDebounceMs
    );
    if (this.settings.stagingPushOnSave || this.settings.autoBackupOnSave) {
      this.modifyEventRef = this.app.vault.on("modify", async (file) => {
        if (!(file instanceof import_obsidian6.TFile))
          return;
        if (this.isExcluded(file.path))
          return;
        if (!this.isWatchedExtension(file))
          return;
        if (!await this.hasContentChanged(file))
          return;
        this.pendingModifiedFiles.add(file.path);
        if (this.debouncedSavePending) {
          this.debouncedSavePending();
        }
        if (this.debouncedAutoBackup) {
          this.debouncedAutoBackup();
        }
      });
      this.registerEvent(this.modifyEventRef);
    }
  }
  isBinaryFile(file) {
    const binaryExtensions = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp", "ico", "pdf", "mp3", "wav", "ogg", "m4a", "flac", "mp4", "webm", "mov", "zip", "gz", "tar", "7z", "rar"]);
    return binaryExtensions.has(file.extension.toLowerCase());
  }
  async encodeFileContent(file) {
    if (this.isBinaryFile(file)) {
      const data = await this.app.vault.readBinary(file);
      const bytes = new Uint8Array(data);
      let binary = "";
      for (let i = 0; i < bytes.length; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      return btoa(binary);
    }
    const content = await this.app.vault.read(file);
    return btoa(unescape(encodeURIComponent(content)));
  }
  async stagingPushPendingFiles() {
    var _a, _b;
    if (this.vaultSourceId === 0)
      return;
    const filePaths = Array.from(this.pendingModifiedFiles);
    this.pendingModifiedFiles.clear();
    await this.clearPendingCache();
    if (filePaths.length === 0)
      return;
    const files = [];
    const failedPaths = [];
    for (const filePath of filePaths) {
      try {
        const file = this.app.vault.getAbstractFileByPath(filePath);
        if (!(file instanceof import_obsidian6.TFile))
          continue;
        const encoded = await this.encodeFileContent(file);
        const stat = await this.app.vault.adapter.stat(file.path);
        files.push({
          rel_path: file.path.replace(/\\/g, "/"),
          action: "modify",
          content: encoded,
          size: (_a = stat == null ? void 0 : stat.size) != null ? _a : 0,
          mtime: (_b = stat == null ? void 0 : stat.mtime) != null ? _b : Date.now() * 1e3
        });
      } catch (e) {
        failedPaths.push(filePath);
      }
    }
    if (files.length === 0) {
      for (const p of failedPaths)
        this.pendingModifiedFiles.add(p);
      if (failedPaths.length > 0)
        await this.savePendingCache();
      return;
    }
    try {
      const result = await this.client.stagingPush({
        source_id: this.vaultSourceId,
        message: `Obsidian: ${files.length} file${files.length > 1 ? "s" : ""}`,
        files,
        trigger: "api"
      });
      const names = files.map((f) => f.rel_path.split("/").pop()).join(", ");
      new import_obsidian6.Notice(`Ginkgo: \u5DF2\u63A8\u9001 ${files.length} \u4E2A\u6587\u4EF6 (${names})`, 4e3);
      this.saveHashCache();
      if (failedPaths.length > 0) {
        for (const p of failedPaths)
          this.pendingModifiedFiles.add(p);
        await this.savePendingCache();
      }
    } catch (err) {
      this.handleError(err, "\u63A8\u9001\u5931\u8D25");
      for (const p of filePaths)
        this.pendingModifiedFiles.add(p);
      await this.savePendingCache();
    }
  }
  async stagingPushFile(file) {
    var _a, _b;
    if (this.vaultSourceId === 0) {
      new import_obsidian6.Notice("Ginkgo: \u8BF7\u5148\u914D\u7F6E\u5907\u4EFD\u6E90");
      return;
    }
    try {
      if (!await this.hasContentChanged(file)) {
        new import_obsidian6.Notice("Ginkgo: \u6587\u4EF6\u5185\u5BB9\u672A\u53D8\u5316\uFF0C\u8DF3\u8FC7\u63A8\u9001");
        return;
      }
      const encoded = await this.encodeFileContent(file);
      const relPath = file.path.replace(/\\/g, "/");
      const stat = await this.app.vault.adapter.stat(file.path);
      const filePush = {
        rel_path: relPath,
        action: "modify",
        content: encoded,
        size: (_a = stat == null ? void 0 : stat.size) != null ? _a : 0,
        mtime: (_b = stat == null ? void 0 : stat.mtime) != null ? _b : Date.now() * 1e3
      };
      const result = await this.client.stagingPush({
        source_id: this.vaultSourceId,
        message: `Obsidian: ${file.name}`,
        files: [filePush],
        trigger: "api"
      });
      new import_obsidian6.Notice(`Ginkgo: \u5DF2\u63A8\u9001 ${file.name} (session: ${result.session_id.slice(0, 8)})`);
      if (!this.isBinaryFile(file)) {
        const content = await this.app.vault.read(file);
        this.lastPushedHashes.set(file.path, await this.contentHash(content));
      }
      this.saveHashCache();
    } catch (err) {
      this.handleError(err, "\u63A8\u9001\u5931\u8D25");
    }
  }
  async backupVault() {
    if (this.vaultSourceId === 0) {
      await this.setupSource();
      if (this.vaultSourceId === 0)
        return;
    }
    this.updateStatusBar("backing_up");
    new import_obsidian6.Notice("Ginkgo: \u5907\u4EFD\u5DF2\u5F00\u59CB");
    try {
      await this.client.triggerBackup(this.vaultSourceId);
      this.startProgressPolling();
    } catch (err) {
      this.handleError(err, "\u5907\u4EFD\u5931\u8D25");
      this.updateStatusBar("error");
    }
  }
  async cancelBackup() {
    try {
      await this.client.cancelBackup(this.vaultSourceId);
      new import_obsidian6.Notice("Ginkgo: \u5907\u4EFD\u5DF2\u53D6\u6D88");
      this.updateStatusBar("connected");
    } catch (err) {
      this.handleError(err, "\u53D6\u6D88\u5907\u4EFD\u5931\u8D25");
    }
  }
  startProgressPolling() {
    if (this.progressTimer)
      window.clearInterval(this.progressTimer);
    this.progressTimer = window.setInterval(async () => {
      try {
        const progress = await this.client.getProgress(this.vaultSourceId);
        if (!progress || progress.phase === "complete" || progress.phase === "error" || progress.phase === "cancelled") {
          window.clearInterval(this.progressTimer);
          this.progressTimer = void 0;
          if ((progress == null ? void 0 : progress.phase) === "complete") {
            new import_obsidian6.Notice("Ginkgo: \u5907\u4EFD\u5B8C\u6210");
            this.updateStatusBar("connected");
          } else if ((progress == null ? void 0 : progress.phase) === "error") {
            new import_obsidian6.Notice("Ginkgo: \u5907\u4EFD\u51FA\u9519");
            this.updateStatusBar("error");
          } else {
            this.updateStatusBar("connected");
          }
          return;
        }
        const pct = progress.total_files > 0 ? Math.round(progress.processed_files / progress.total_files * 100) : 0;
        this.updateStatusBar("backing_up", `${pct}%`);
      } catch (e) {
      }
    }, 3e3);
  }
  async setupSource(repoPaths) {
    const vaultPath = this.getVaultPath();
    if (!vaultPath) {
      new import_obsidian6.Notice("Ginkgo: \u65E0\u6CD5\u786E\u5B9A Vault \u8DEF\u5F84");
      return;
    }
    if (!repoPaths || repoPaths.length === 0) {
      new import_obsidian6.Notice("Ginkgo: \u8BF7\u5148\u9009\u62E9\u5907\u4EFD\u4ED3\u5E93");
      return;
    }
    const vaultName = this.app.vault.getName();
    new import_obsidian6.Notice("Ginkgo: \u6B63\u5728\u914D\u7F6E\u5907\u4EFD\u6E90...");
    try {
      const source = await this.client.ensureSourceExists(
        vaultPath,
        vaultName,
        repoPaths,
        this.settings.excludePaths
      );
      if (source) {
        this.vaultSourceId = source.id;
        this.vaultRepoPath = source.repo_paths.length > 0 ? source.repo_paths[0] : "";
        this.settings.sourceId = source.id;
        await this.saveSettings();
        const repoList = (source.repo_paths || []).join(", ");
        new import_obsidian6.Notice(`Ginkgo: ${vaultName} \u5DF2\u914D\u7F6E\uFF08\u4ED3\u5E93: ${repoList}\uFF09`, 6e3);
        this.updateStatusBar("connected");
      } else {
        new import_obsidian6.Notice("Ginkgo: \u521B\u5EFA\u5907\u4EFD\u6E90\u5931\u8D25");
      }
    } catch (err) {
      this.handleError(err, "\u914D\u7F6E\u5907\u4EFD\u6E90\u5931\u8D25");
    }
  }
  async checkStatus() {
    try {
      const status = await this.client.getStatus();
      const lines = [
        `\u5907\u4EFD\u6E90: ${status.source_count} \u4E2A`,
        `\u5FEB\u7167: ${status.snapshot_count} \u4E2A`,
        `\u5B58\u50A8: ${this.formatBytes(status.storage_used)}`,
        `\u72B6\u6001: ${status.backup_running ? "\u5907\u4EFD\u4E2D" : "\u7A7A\u95F2"}`
      ];
      new import_obsidian6.Notice(`Ginkgo \u72B6\u6001
${lines.join("\n")}`, 8e3);
    } catch (err) {
      this.handleError(err, "\u83B7\u53D6\u72B6\u6001\u5931\u8D25");
    }
  }
  openTimeline() {
    const existing = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const rightLeaf = this.app.workspace.getRightLeaf(false);
    if (rightLeaf) {
      rightLeaf.setViewState({ type: TIMELINE_VIEW_TYPE, active: true });
      this.app.workspace.revealLeaf(rightLeaf);
    }
  }
  async showFileHistory(file) {
    if (this.vaultSourceId === 0) {
      new import_obsidian6.Notice("Ginkgo: \u5F53\u524D Vault \u672A\u914D\u7F6E\u5907\u4EFD\u6E90");
      return;
    }
    const { FileHistoryModal: FileHistoryModal2 } = await Promise.resolve().then(() => (init_file_history_modal(), file_history_modal_exports));
    const modal = new FileHistoryModal2(this.app, this.client, this.vaultSourceId, file.path, this.vaultRepoPath);
    modal.open();
  }
  async showFileHistoryByPath(filePath) {
    if (this.vaultSourceId === 0) {
      new import_obsidian6.Notice("Ginkgo: \u5F53\u524D Vault \u672A\u914D\u7F6E\u5907\u4EFD\u6E90");
      return;
    }
    const { FileHistoryModal: FileHistoryModal2 } = await Promise.resolve().then(() => (init_file_history_modal(), file_history_modal_exports));
    const modal = new FileHistoryModal2(this.app, this.client, this.vaultSourceId, filePath, this.vaultRepoPath);
    modal.open();
  }
  openGinkgoApp() {
    const host = this.settings.apiHost;
    const port = this.settings.apiPort;
    let url;
    if (host.startsWith("http://") || host.startsWith("https://")) {
      const u = new URL(host);
      if (port && !host.includes(":" + port)) {
        u.port = String(port);
      }
      url = u.origin;
    } else {
      url = `http://${host}:${port}`;
    }
    window.open(url, "_blank");
  }
  startStatusRefresh() {
    if (this.refreshTimer)
      window.clearInterval(this.refreshTimer);
    const interval = this.connected ? this.settings.refreshInterval * 1e3 : 1e4;
    this.refreshTimer = window.setInterval(() => this.refreshStatus(), interval);
  }
  async refreshStatus() {
    var _a;
    try {
      const connected = await this.client.isConnected();
      if (!connected) {
        this.connected = false;
        this.consecutiveFailures++;
        this.updateStatusBar("disconnected");
        if (this.consecutiveFailures === 1 && this.settings.stagingPushOnSave) {
          new import_obsidian6.Notice("Ginkgo: \u672A\u8FDE\u63A5\uFF0C\u81EA\u52A8\u5907\u4EFD\u5DF2\u6682\u505C", 5e3);
        }
        return;
      }
      const wasDisconnected = !this.connected;
      this.connected = true;
      this.consecutiveFailures = 0;
      if (wasDisconnected && this.settings.stagingPushOnSave && this.pendingModifiedFiles.size > 0 && this.vaultSourceId > 0) {
        this.stagingPushPendingFiles();
      }
      const progressArr = await this.client.getProgress();
      const progress = Array.isArray(progressArr) ? progressArr[0] : progressArr;
      if (progress && progress.phase && progress.phase !== "complete" && progress.phase !== "error" && progress.phase !== "cancelled") {
        const pct = progress.total_files > 0 ? Math.round(progress.processed_files / progress.total_files * 100) : 0;
        this.updateStatusBar("backing_up", `${pct}%`);
        return;
      }
      if (this.vaultSourceId > 0) {
        const sources = await this.client.getSources();
        const vaultSource = sources.find((s) => s.id === this.vaultSourceId);
        if (vaultSource) {
          const fileCount = (_a = vaultSource.file_count) != null ? _a : 0;
          const lastBackup = vaultSource.last_backup > 0 ? this.formatRelativeTime(new Date(vaultSource.last_backup / 1e6)) : "\u4ECE\u672A";
          this.updateStatusBar("connected", `${fileCount} \u6587\u4EF6 | ${lastBackup}`);
          return;
        }
      }
      this.updateStatusBar("connected");
    } catch (e) {
      this.connected = false;
      this.updateStatusBar("disconnected");
    }
  }
  updateStatusBar(state, detail) {
    this.statusBarItem.empty();
    const icon = this.statusBarItem.createSpan({ cls: "ginkgo-status-icon" });
    (0, import_obsidian6.setIcon)(icon, "hard-drive");
    const textSpan = this.statusBarItem.createSpan();
    switch (state) {
      case "connected":
        icon.addClass("ginkgo-status-ok");
        textSpan.setText(detail ? ` ${detail}` : " \u5DF2\u8FDE\u63A5");
        this.statusBarItem.setAttribute("aria-label", "Ginkgo Backup \u5DF2\u8FDE\u63A5");
        break;
      case "disconnected":
        icon.addClass("ginkgo-status-err");
        textSpan.setText(" \u672A\u8FDE\u63A5");
        this.statusBarItem.setAttribute("aria-label", "Ginkgo Backup \u672A\u8FDE\u63A5");
        break;
      case "backing_up":
        icon.addClass("ginkgo-status-active");
        textSpan.setText(detail ? ` \u5907\u4EFD\u4E2D ${detail}` : " \u5907\u4EFD\u4E2D...");
        this.statusBarItem.setAttribute("aria-label", "\u6B63\u5728\u5907\u4EFD");
        break;
      case "error":
        icon.addClass("ginkgo-status-err");
        textSpan.setText(" \u9519\u8BEF");
        this.statusBarItem.setAttribute("aria-label", "\u5907\u4EFD\u51FA\u9519");
        break;
      default:
        textSpan.setText(" \u8FDE\u63A5\u4E2D...");
        break;
    }
  }
  showStatusBarMenu(event) {
    const menu = new import_obsidian6.Menu();
    menu.addItem((item) => {
      item.setTitle("\u7ACB\u5373\u5907\u4EFD").setIcon("upload").onClick(() => this.backupVault());
    });
    menu.addItem((item) => {
      item.setTitle("\u53D6\u6D88\u5907\u4EFD").setIcon("x").onClick(() => this.cancelBackup());
    });
    menu.addItem((item) => {
      item.setTitle("\u63A8\u9001\u5F53\u524D\u6587\u4EF6").setIcon("file-plus").onClick(() => {
        const file = this.app.workspace.getActiveFile();
        if (file)
          this.stagingPushFile(file);
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u67E5\u770B\u65F6\u95F4\u7EBF").setIcon("calendar").onClick(() => this.openTimeline());
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u68C0\u67E5\u72B6\u6001").setIcon("activity").onClick(() => this.checkStatus());
    });
    if (this.vaultSourceId === 0) {
      menu.addItem((item) => {
        item.setTitle("\u914D\u7F6E\u5907\u4EFD").setIcon("settings").onClick(() => this.setupSource());
      });
    }
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u6253\u5F00\u5E94\u7528").setIcon("globe").onClick(() => this.openGinkgoApp());
    });
    menu.showAtMouseEvent(event);
  }
  handleError(err, prefix) {
    if (err instanceof GinkgoApiError) {
      new import_obsidian6.Notice(`Ginkgo: ${prefix} \u2014 ${err.userMessage}`, 8e3);
    } else {
      const msg = err instanceof Error ? err.message : String(err);
      new import_obsidian6.Notice(`Ginkgo: ${prefix} \u2014 ${msg}`, 8e3);
    }
  }
  formatBytes(bytes) {
    if (bytes < 1024)
      return `${bytes} B`;
    if (bytes < 1048576)
      return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1073741824)
      return `${(bytes / 1048576).toFixed(1)} MB`;
    return `${(bytes / 1073741824).toFixed(1)} GB`;
  }
  formatRelativeTime(date) {
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 6e4);
    if (diffMins < 1)
      return "\u521A\u521A";
    if (diffMins < 60)
      return `${diffMins}\u5206\u949F\u524D`;
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24)
      return `${diffHours}\u5C0F\u65F6\u524D`;
    const diffDays = Math.floor(diffHours / 24);
    return `${diffDays}\u5929\u524D`;
  }
};
